# Training Loss
train_criterion: "RSPointmapHeightLoss(pointmap_criterion=L1Loss(reduction='none'), height_criterion=L1Loss(reduction='none'), pointmap_loss_weight=1.0, height_loss_weight=0.1)"
# Validation Loss
test_criterion: "RSPointmapHeightLoss(pointmap_criterion=L1Loss(reduction='none'), height_criterion=L1Loss(reduction='none'), pointmap_loss_weight=1.0, height_loss_weight=0.1)"
