# String for model factory
model_str: "pi3_modality_embedding"
# Model config
model_config:
  name: "pi3_modality_embedding"
  load_pretrained_weights: true
# Image Normalization Type
data_norm_type: "identity"
pretrained: null
torch_hub_force_reload: False
