defaults:
  - default
  - vigor_chicago_wai: default

num_workers: 0
num_views: 2
resolution_train: ${dataset.resolution_options.518_1_00_ar}
resolution_val: ${dataset.resolution_options.518_1_00_ar}

train_dataset: null
test_dataset_aerial:
  "VigorChicagoWAI(
    split='val',
    resolution=${dataset.resolution_val},
    principal_point_centered=${dataset.vigor_chicago_wai.val.principal_point_centered},
    seed=${dataset.vigor_chicago_wai.val.seed},
    transform='imgnorm',
    data_norm_type='${model.data_norm_type}',
    ROOT='${dataset.vigor_chicago_wai.val.ROOT}',
    dataset_metadata_dir='${dataset.vigor_chicago_wai.val.dataset_metadata_dir}',
    overfit_num_sets=None,
    scene_list_path='${mapanything_dataset_metadata_dir}/Crossview_rs_aerial/val/Crossview_rs_aerial_scene_list_val.npy',
    cities=${dataset.vigor_chicago_wai.val.cities},
    variable_num_views=${dataset.val.variable_num_views},
    num_views=${dataset.num_views},
    covisibility_thres=${dataset.vigor_chicago_wai.val.covisibility_thres})"
test_dataset_remote:
  "VigorChicagoRSAerial(
    metadata_root='${mapanything_dataset_metadata_dir}/Crossview_rs_aerial',
    split='val',
    providers=${dataset.vigor_chicago_rs_aerial_benchmark.remote.providers},
    overfit_num_sets=${dataset.vigor_chicago_rs_aerial_benchmark.remote.overfit_num_sets},
    cities=${dataset.vigor_chicago_rs_aerial_benchmark.remote.cities},
    load_aerial_scene_meta=False,
    transform='imgnorm',
    resolution=${dataset.vigor_chicago_rs_aerial_benchmark.remote.dataset_resolution},
    num_augmented_crops_per_sample=${dataset.vigor_chicago_rs_aerial_benchmark.remote.num_augmented_crops_per_sample},
    crop_mode='${dataset.vigor_chicago_rs_aerial_benchmark.remote.crop_mode}',
    crop_scale_range=${dataset.vigor_chicago_rs_aerial_benchmark.remote.crop_scale_range},
    image_resize_mode='${dataset.vigor_chicago_rs_aerial_benchmark.remote.image_resize_mode}',
    label_resize_mode='${dataset.vigor_chicago_rs_aerial_benchmark.remote.label_resize_mode}')"

vigor_chicago_rs_aerial_benchmark:
  remote:
    providers: ['Google_Satellite']
    overfit_num_sets: null
    cities: []
    dataset_resolution: ${dataset.resolution_val}
    num_augmented_crops_per_sample: 1
    crop_mode: 'none'
    crop_scale_range: [0.7, 1.0]
    image_resize_mode: 'nearest'
    label_resize_mode: 'nearest'
