defaults:
  - default

num_workers: 4
num_views: 4
resolution_train: ${dataset.resolution_options.518_1_00_ar}
resolution_val: ${dataset.resolution_options.518_1_00_ar}

train_dataset: ${dataset.vigor_chicago_joint_rs_aerial.train.dataset_str}
test_dataset:
  "+ 40 @ ${dataset.vigor_chicago_joint_rs_aerial.val.dataset_str}
  + 40 @ ${dataset.vigor_chicago_joint_rs_aerial.test.dataset_str}"

vigor_chicago_joint_rs_aerial:
  train:
    dataset_str:
      "VigorChicagoJointRSAerial(
        split='${dataset.vigor_chicago_joint_rs_aerial.train.split}',
        resolution=${dataset.vigor_chicago_joint_rs_aerial.train.dataset_resolution},
        principal_point_centered=${dataset.vigor_chicago_joint_rs_aerial.train.principal_point_centered},
        aug_crop=${dataset.vigor_chicago_joint_rs_aerial.train.aug_crop},
        transform='${dataset.vigor_chicago_joint_rs_aerial.train.transform}',
        data_norm_type='${dataset.vigor_chicago_joint_rs_aerial.train.data_norm_type}',
        ROOT='${dataset.vigor_chicago_joint_rs_aerial.train.ROOT}',
        dataset_metadata_dir='${dataset.vigor_chicago_joint_rs_aerial.train.dataset_metadata_dir}',
        cities=${dataset.vigor_chicago_joint_rs_aerial.train.cities},
        overfit_num_sets=${dataset.vigor_chicago_joint_rs_aerial.train.overfit_num_sets},
        variable_num_views=${dataset.vigor_chicago_joint_rs_aerial.train.variable_num_views},
        num_views=${dataset.vigor_chicago_joint_rs_aerial.train.num_views},
        covisibility_thres=${dataset.vigor_chicago_joint_rs_aerial.train.covisibility_thres},
        remote_ROOT='${dataset.vigor_chicago_joint_rs_aerial.train.remote_ROOT}',
        remote_providers=${dataset.vigor_chicago_joint_rs_aerial.train.remote_providers},
        remote_provider_sampling_mode='${dataset.vigor_chicago_joint_rs_aerial.train.remote_provider_sampling_mode}',
        remote_resolution=${dataset.vigor_chicago_joint_rs_aerial.train.remote_resolution},
        remote_transform='${dataset.vigor_chicago_joint_rs_aerial.train.remote_transform}',
        skip_missing_remote=${dataset.vigor_chicago_joint_rs_aerial.train.skip_missing_remote},
        remote_crop_mode='${dataset.vigor_chicago_joint_rs_aerial.train.remote_crop_mode}',
        remote_crop_scale_range=${dataset.vigor_chicago_joint_rs_aerial.train.remote_crop_scale_range},
        remote_image_resize_mode='${dataset.vigor_chicago_joint_rs_aerial.train.remote_image_resize_mode}',
        remote_label_resize_mode='${dataset.vigor_chicago_joint_rs_aerial.train.remote_label_resize_mode}')"
    split: 'train'
    dataset_resolution: ${dataset.resolution_train}
    principal_point_centered: ${dataset.principal_point_centered}
    aug_crop: 16
    transform: 'colorjitter+grayscale+gaublur'
    data_norm_type: ${model.data_norm_type}
    ROOT: ${root_data_dir}/Crossview_wai
    dataset_metadata_dir: ${mapanything_dataset_metadata_dir}/Crossview
    overfit_num_sets: null
    variable_num_views: ${dataset.train.variable_num_views}
    num_views: ${dataset.num_views}
    covisibility_thres: 0.05
    remote_ROOT: ${root_data_dir}/Crossview_rs
    remote_providers: ['Google_Satellite']
    remote_provider_sampling_mode: 'first_available'
    remote_resolution: ${dataset.resolution_train}
    remote_transform: 'imgnorm'
    skip_missing_remote: false
    remote_crop_mode: 'none'
    remote_crop_scale_range: [1.0, 1.0]
    remote_image_resize_mode: 'nearest'
    remote_label_resize_mode: 'nearest'
    cities: []
  val:
    dataset_str:
      "VigorChicagoJointRSAerial(
        split='${dataset.vigor_chicago_joint_rs_aerial.val.split}',
        resolution=${dataset.vigor_chicago_joint_rs_aerial.val.dataset_resolution},
        principal_point_centered=${dataset.vigor_chicago_joint_rs_aerial.val.principal_point_centered},
        seed=${dataset.vigor_chicago_joint_rs_aerial.val.seed},
        transform='${dataset.vigor_chicago_joint_rs_aerial.val.transform}',
        data_norm_type='${dataset.vigor_chicago_joint_rs_aerial.val.data_norm_type}',
        ROOT='${dataset.vigor_chicago_joint_rs_aerial.val.ROOT}',
        dataset_metadata_dir='${dataset.vigor_chicago_joint_rs_aerial.val.dataset_metadata_dir}',
        cities=${dataset.vigor_chicago_joint_rs_aerial.val.cities},
        overfit_num_sets=${dataset.vigor_chicago_joint_rs_aerial.val.overfit_num_sets},
        variable_num_views=${dataset.vigor_chicago_joint_rs_aerial.val.variable_num_views},
        num_views=${dataset.vigor_chicago_joint_rs_aerial.val.num_views},
        covisibility_thres=${dataset.vigor_chicago_joint_rs_aerial.val.covisibility_thres},
        remote_ROOT='${dataset.vigor_chicago_joint_rs_aerial.val.remote_ROOT}',
        remote_providers=${dataset.vigor_chicago_joint_rs_aerial.val.remote_providers},
        remote_provider_sampling_mode='${dataset.vigor_chicago_joint_rs_aerial.val.remote_provider_sampling_mode}',
        remote_resolution=${dataset.vigor_chicago_joint_rs_aerial.val.remote_resolution},
        remote_transform='${dataset.vigor_chicago_joint_rs_aerial.val.remote_transform}',
        skip_missing_remote=${dataset.vigor_chicago_joint_rs_aerial.val.skip_missing_remote},
        remote_crop_mode='${dataset.vigor_chicago_joint_rs_aerial.val.remote_crop_mode}',
        remote_crop_scale_range=${dataset.vigor_chicago_joint_rs_aerial.val.remote_crop_scale_range},
        remote_image_resize_mode='${dataset.vigor_chicago_joint_rs_aerial.val.remote_image_resize_mode}',
        remote_label_resize_mode='${dataset.vigor_chicago_joint_rs_aerial.val.remote_label_resize_mode}')"
    split: 'val'
    dataset_resolution: ${dataset.resolution_val}
    principal_point_centered: ${dataset.principal_point_centered}
    seed: 777
    transform: 'imgnorm'
    data_norm_type: ${model.data_norm_type}
    ROOT: ${root_data_dir}/Crossview_wai
    dataset_metadata_dir: ${mapanything_dataset_metadata_dir}/Crossview
    overfit_num_sets: null
    variable_num_views: ${dataset.val.variable_num_views}
    num_views: ${dataset.num_views}
    covisibility_thres: 0.05
    remote_ROOT: ${root_data_dir}/Crossview_rs
    remote_providers: ['Google_Satellite']
    remote_provider_sampling_mode: 'first_available'
    remote_resolution: ${dataset.resolution_val}
    remote_transform: 'imgnorm'
    skip_missing_remote: false
    remote_crop_mode: 'none'
    remote_crop_scale_range: [1.0, 1.0]
    remote_image_resize_mode: 'nearest'
    remote_label_resize_mode: 'nearest'
    cities: []
  test:
    dataset_str:
      "VigorChicagoJointRSAerial(
        split='${dataset.vigor_chicago_joint_rs_aerial.test.split}',
        resolution=${dataset.vigor_chicago_joint_rs_aerial.test.dataset_resolution},
        principal_point_centered=${dataset.vigor_chicago_joint_rs_aerial.test.principal_point_centered},
        seed=${dataset.vigor_chicago_joint_rs_aerial.test.seed},
        transform='${dataset.vigor_chicago_joint_rs_aerial.test.transform}',
        data_norm_type='${dataset.vigor_chicago_joint_rs_aerial.test.data_norm_type}',
        ROOT='${dataset.vigor_chicago_joint_rs_aerial.test.ROOT}',
        dataset_metadata_dir='${dataset.vigor_chicago_joint_rs_aerial.test.dataset_metadata_dir}',
        cities=${dataset.vigor_chicago_joint_rs_aerial.test.cities},
        overfit_num_sets=${dataset.vigor_chicago_joint_rs_aerial.test.overfit_num_sets},
        variable_num_views=${dataset.vigor_chicago_joint_rs_aerial.test.variable_num_views},
        num_views=${dataset.vigor_chicago_joint_rs_aerial.test.num_views},
        covisibility_thres=${dataset.vigor_chicago_joint_rs_aerial.test.covisibility_thres},
        remote_ROOT='${dataset.vigor_chicago_joint_rs_aerial.test.remote_ROOT}',
        remote_providers=${dataset.vigor_chicago_joint_rs_aerial.test.remote_providers},
        remote_provider_sampling_mode='${dataset.vigor_chicago_joint_rs_aerial.test.remote_provider_sampling_mode}',
        remote_resolution=${dataset.vigor_chicago_joint_rs_aerial.test.remote_resolution},
        remote_transform='${dataset.vigor_chicago_joint_rs_aerial.test.remote_transform}',
        skip_missing_remote=${dataset.vigor_chicago_joint_rs_aerial.test.skip_missing_remote},
        remote_crop_mode='${dataset.vigor_chicago_joint_rs_aerial.test.remote_crop_mode}',
        remote_crop_scale_range=${dataset.vigor_chicago_joint_rs_aerial.test.remote_crop_scale_range},
        remote_image_resize_mode='${dataset.vigor_chicago_joint_rs_aerial.test.remote_image_resize_mode}',
        remote_label_resize_mode='${dataset.vigor_chicago_joint_rs_aerial.test.remote_label_resize_mode}')"
    split: 'test'
    dataset_resolution: ${dataset.resolution_val}
    principal_point_centered: ${dataset.principal_point_centered}
    seed: 777
    transform: 'imgnorm'
    data_norm_type: ${model.data_norm_type}
    ROOT: ${root_data_dir}/Crossview_wai
    dataset_metadata_dir: ${mapanything_dataset_metadata_dir}/Crossview
    overfit_num_sets: null
    variable_num_views: ${dataset.test.variable_num_views}
    num_views: ${dataset.num_views}
    covisibility_thres: 0.05
    remote_ROOT: ${root_data_dir}/Crossview_rs
    remote_providers: ['Google_Satellite']
    remote_provider_sampling_mode: 'first_available'
    remote_resolution: ${dataset.resolution_val}
    remote_transform: 'imgnorm'
    skip_missing_remote: false
    remote_crop_mode: 'none'
    remote_crop_scale_range: [1.0, 1.0]
    remote_image_resize_mode: 'nearest'
    remote_label_resize_mode: 'nearest'
    cities: []
